from sqlalchemy import Column, Integer, String, DateTime, Text
from Config.db import BASE
from datetime import datetime

class IntranetVerificacionModel(BASE):
    __tablename__ = 'intranet_verificacion_items'
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    lugar_inspeccion_id = Column(String(255), nullable=False)
    responsable_verificacion_id = Column(Integer, nullable=False)
    aspectos_1 = Column(Integer, nullable=False)
    aspectos_2 = Column(Integer, nullable=False)
    aspectos_3 = Column(Integer, nullable=False)
    aspectos_4 = Column(Integer, nullable=False)
    paredes_1 = Column(Integer, nullable=False)
    paredes_2 = Column(Integer, nullable=False)
    paredes_3 = Column(Integer, nullable=False)
    paredes_4 = Column(Integer, nullable=False)
    puertas_1 = Column(Integer, nullable=False)
    puertas_2 = Column(Integer, nullable=False)
    puertas_3 = Column(Integer, nullable=False)
    puertas_4 = Column(Integer, nullable=False)
    puertas_5 = Column(Integer, nullable=False)
    pisos_1 = Column(Integer, nullable=False)
    pisos_2 = Column(Integer, nullable=False)
    pisos_3 = Column(Integer, nullable=False)
    pisos_4 = Column(Integer, nullable=False)
    techo_1 = Column(Integer, nullable=False)
    techo_2 = Column(Integer, nullable=False)
    techo_3 = Column(Integer, nullable=False)
    seguridad_1 = Column(Integer, nullable=False)
    seguridad_2 = Column(Integer, nullable=False)
    seguridad_3 = Column(Integer, nullable=False)
    seguridad_4 = Column(Integer, nullable=False)
    novedades = Column(Text, nullable=True)
    estado = Column(Integer, default=1)
    created_at = Column(DateTime, default=datetime.now)

    def __init__(self, data):
        self.lugar_inspeccion_id = data.get("lugar_inspeccion_id")
        self.responsable_verificacion_id = data.get("responsable_verificacion_id")
        self.aspectos_1 = data.get("aspectos_1")
        self.aspectos_2 = data.get("aspectos_2")
        self.aspectos_3 = data.get("aspectos_3")
        self.aspectos_4 = data.get("aspectos_4")
        self.paredes_1 = data.get("paredes_1")
        self.paredes_2 = data.get("paredes_2")
        self.paredes_3 = data.get("paredes_3")
        self.paredes_4 = data.get("paredes_4")
        self.puertas_1 = data.get("puertas_1")
        self.puertas_2 = data.get("puertas_2")
        self.puertas_3 = data.get("puertas_3")
        self.puertas_4 = data.get("puertas_4")
        self.puertas_5 = data.get("puertas_5")
        self.pisos_1 = data.get("pisos_1")
        self.pisos_2 = data.get("pisos_2")
        self.pisos_3 = data.get("pisos_3")
        self.pisos_4 = data.get("pisos_4")
        self.techo_1 = data.get("techo_1")
        self.techo_2 = data.get("techo_2")
        self.techo_3 = data.get("techo_3")
        self.seguridad_1 = data.get("seguridad_1")
        self.seguridad_2 = data.get("seguridad_2")
        self.seguridad_3 = data.get("seguridad_3")
        self.seguridad_4 = data.get("seguridad_4")
        self.novedades = data.get("novedades")
